export const LOAD_QUIZ = 'LOAD_QUIZ';
export const GENERATE_QUIZ = 'GENERATE_QUIZ';
export const SET_ANSWER = 'SET_ANSWER';
export const SUBMIT_ANSWERS = 'SUBMIT_ANSWERS';
export const GET_LEADERBOARDS = 'GET_LEADERBOARDS';
export const GET_VALIDQUIZCODES = 'GET_VALIDQUIZCODES';
export const GET_VALIDQUIZOPTIONS = 'GET_VALIDQUIZOPTIONS';
