package models

object ActionTypes {
  val LOAD_QUIZ = "LOAD_QUIZ"
  val GENERATE_QUIZ = "GENERATE_QUIZ"
  val SET_ANSWER = "SET_ANSWER"
  val SUBMIT_ANSWERS = "SUBMIT_ANSWERS"
  val GET_LEADERBOARDS = "GET_LEADERBOARDS"
  val GET_VALIDQUIZCODES = "GET_VALIDQUIZCODES"
  val GET_VALIDQUIZOPTIONS = "GET_VALIDQUIZOPTIONS"
}
